name = "cisadex"
compatibility_date = "2025-08-08"
pages_build_output_dir = "dist"
# compatibility_flags = ["nodejs_compat"]  # not required here

[[d1_databases]]
binding = "DB"
database_name = "cisadex-ti"
database_id = "5da7e67b-d0d0-4e5e-b87b-bcbdfb12368e"

# (Optional if APIs need CACHE)

# [[kv_namespaces]]
# binding = "CACHE"
# id = "REPLACE_WITH_YOUR_KV_ID"
