name = "cisadex"
compatibility_date = "2025-08-08"
pages_build_output_dir = "dist"
# compatibility_flags = ["nodejs_compat"]  # not required here

[[d1_databases]]
binding = "DB"
database_name = "cisadex-ti"
 # TODO: replace with real D1 database ID after running `wrangler d1 create cisadex-ti`
 database_id = "01e39ad4-00ea-4398-9d58-00e70df9d6f5"

# (Optional if APIs need CACHE)

# [[kv_namespaces]]
# binding = "CACHE"
# id = "REPLACE_WITH_YOUR_KV_ID"
