name = "cisadex-ti-worker"
main = "src/index.mjs"
compatibility_date = "2025-08-08"

[triggers]
crons = ["*/15 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "cisadex-ti"
 # TODO: replace with real D1 database ID after running `wrangler d1 create cisadex-ti`
 database_id = "5da7e67b-d0d0-4e5e-b87b-bcbdfb12368e"


[[kv_namespaces]]
binding = "CACHE"
id = "REPLACE_WITH_YOUR_KV_ID"

[[queues.producers]]
binding = "ENRICH_QUEUE"
queue = "enrich-queue"

[[queues.consumers]]
queue = "enrich-queue"
